# require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4
  Exclude:
    - db/**/*
    - script/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - spec/fixtures/**/*
    - config/initializers/**/*
    - config/environments/**/*
    - config/application.rb
    - config/routes.rb
    - ./Gemfile
    - ./Rakefile
    - ./config.ru

# Rails:
#   Enabled: true

Documentation:
  Enabled: false

Layout/MultilineBlockLayout:
  Exclude:
    - spec/**/*

Layout/TrailingBlankLines:
  Enabled: false

Layout/IndentHash:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/StructInheritance:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i':   '[]'
    '%I':   '[]'
    '%r':   '{}'
    '%w':   '[]'
    '%W':   '[]'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - spec/**/*
    - features/**/*

Metrics/MethodLength:
  Enabled: true
  Max: 20
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/**/*
