# require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.5.0
  Exclude:
    - db/**/*
    - script/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - config/initializers/**/*
    - config/environments/**/*
    - config/application.rb
    - config/routes.rb
    - ./Gemfile
    - ./Rakefile
    - ./config.ru

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i':   '[]'
    '%I':   '[]'
    '%r':   '{}'
    '%w':   '[]'
    '%W':   '[]'

Layout/LineLength:
  Enabled: true
  Max: 120
