language: ruby

rvm:
  - 2.4.1

script:
  - bundle exec rake

before_script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare

cache: bundler

addons:
  code_climate:
    repo_token: c79183d506a63da6a1d6f5a85e7c64717883b03e696947c64fdfde08001815fd
