language: ruby

rvm:
  - 2.4.1

before_install:
  - export GEM_HOME=$PWD/vendor/bundle/ruby/2.4.1
  - gem install bundler
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database od-ot_test' -U postgres

cache: bundler

addons:
  code_climate:
    repo_token: c79183d506a63da6a1d6f5a85e7c64717883b03e696947c64fdfde08001815fd
