version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build:
      context: .
      dockerfile: ./docker/containers/web/Dockerfile
    volumes:
      - ./:/home/deploy/od-ot
      - gems:/usr/local/bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db

volumes:
  gems:
