version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/containers/postgres/Dockerfile
    volumes:
      - ./:/home/root/project

  web:
    build:
      context: .
      dockerfile: ./docker/containers/web/Dockerfile
    volumes:
      - ./:/home/deploy/od-ot
      - gems:/usr/local/bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    links:
      - postgres
    env_file: .env

volumes:
  gems:
