env:
  RUBY_VERSION: 2.5.9
  PG_USER: postgres
  PG_PASSWORD: postgres

name: CI

on: [push, pull_request]

jobs:
  check_code:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install related Gems
        run: |
          gem install rubocop
          gem install rails_best_practices
          gem install bundle-audit
          gem install brakeman
      - name: Run checks
        run: | 
          rubocop
          rails_best_practices .
          bundle-audit check --update
          brakeman

  rspec:
    name: RSpec
    needs: check_code
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.3
        ports:
        - 5432:5432
        env:
          PG_USER: ${{ env.PG_USER}}
          PG_PASSWORD: ${{ env.PG_PASSWORD }}
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      
      - name: Gem cache
        id: cache-bundle
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      
      - name: Install dependencies
        env:
          RAILS_ENV: test
        run: |
          gem install bundler:1.17.3
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Setup database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.github-actions config/database.yml
          bin/rails db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec
